#!/bin/bash

numb=5000
age=500

if [ $numb -eq $age ];
then
echo "The statemnt is TRUE!!!"
else
echo "The statement is FALSE!!!"
fi

echo

if [ $numb > $age ];
then
    echo "The amount is bigger"
else
    echo "The amount is small"
fi
